/*

 Licensed under the Apache License, Version 2.0 (the "License"); you may not
 use this file except in compliance with the License. You may obtain a copy
 of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 License for the specific language governing permissions and limitations under
 the License.

 Copyright (c) 2011-2012 Almende B.V. <http://www.almende.com>

 @author Jos de Jong <jos@almende.org>
 @date   2012-02-09

 Licensed under the Apache License, Version 2.0 (the "License"); you may not
 use this file except in compliance with the License. You may obtain a copy
 of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 License for the specific language governing permissions and limitations under
 the License.

 Copyright (c) 2011-2012 Almende B.V. <http://links.sourceforge.net>

 @author   Jos de Jong, <jos@almende.org>
 @date    2012-07-03
 @version 1.2.0
*/
typeof links==="undefined"&&(links={});typeof google==="undefined"&&(google=void 0);
links.TreeGrid=function(a,b){if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]==a)return b;return-1};this.options={width:"100%",height:"100%",padding:4,indentationWidth:20,items:{defaultHeight:24,minHeight:24},dropAreaHeight:0};try{b.itemHeight!=void 0&&console.log("WARNING: property option.itemHeight is no longer supported. It is changed to options.items.defaultHeight")}catch(c){}for(b&&links.TreeGrid.extend(this.options,b);a.hasChildNodes();)a.removeChild(a.firstChild);
this.frame=new links.TreeGrid.Frame(a,this.options);this.frame.setTreeGrid(this);this.frame.repaint();this.frame.reflow();this.trigger("ready")};links.TreeGrid.extend=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]instanceof Object?b[c]instanceof Object&&links.TreeGrid.extend(a[c],b[c]):a[c]=b[c])};links.TreeGrid.prototype.draw=function(a,b){b&&links.TreeGrid.extend(this.options,b);this.frame.setGrid(new links.TreeGrid.Grid(a,this.options))};links.TreeGrid.prototype.redraw=function(){if(this.frame)this.frame.onRangeChange()};
links.TreeGrid.Node=function(){this.height=this.left=this.width=this.top=0;this.visible=!0;this.selected=!1};links.TreeGrid.Node.prototype.setParent=function(a){this.parent=a};links.TreeGrid.Node.prototype.getAbsTop=function(){return(this.parent?this.parent.getAbsTop():0)+this.top};links.TreeGrid.Node.prototype.getAbsLeft=function(){return(this.parent?this.parent.getAbsLeft():0)+this.left};links.TreeGrid.Node.prototype.getHeight=function(){return this.height};
links.TreeGrid.Node.prototype.getWidth=function(){return this.width};links.TreeGrid.Node.prototype.getLeft=function(){return this.left};links.TreeGrid.Node.prototype.getTop=function(){return this.top};links.TreeGrid.Node.prototype.setLeft=function(a){this.left=a||0};links.TreeGrid.Node.prototype.setTop=function(a){this.top=a||0};links.TreeGrid.Node.prototype.getTreeGrid=function(){return this.parent?this.parent.getTreeGrid():void 0};
links.TreeGrid.Node.prototype.getSelection=function(){return this.parent?this.parent.getSelection():[]};links.TreeGrid.Node.prototype.getContainer=function(){return this.parent?this.parent.getContainer():void 0};links.TreeGrid.Node.prototype.getVisibleWindow=function(){return this.parent?this.parent.getVisibleWindow():{top:0,left:0,width:0,height:0}};links.TreeGrid.Node.prototype.setVisible=function(a){this.visible=a==!0};
links.TreeGrid.Node.prototype.isVisible=function(){return this.visible&&(this.parent?this.parent.isVisible():!0)};links.TreeGrid.Node.prototype.updateHeight=function(){};links.TreeGrid.Node.prototype.onUpdateHeight=function(a){this.parent&&this.parent.updateHeight(this,a)};links.TreeGrid.Node.prototype.repaint=function(){return!1};links.TreeGrid.Node.prototype.reflow=function(){};links.TreeGrid.Node.prototype.update=function(){};
links.TreeGrid.Node.prototype.hide=function(){this.setVisible(!1);this.repaint();this.reflow()};links.TreeGrid.Node.prototype.show=function(){this.setVisible(!0);this.repaint()};links.TreeGrid.Node.prototype.select=function(){this.selected=!0};links.TreeGrid.Node.prototype.unselect=function(){this.selected=!1};links.TreeGrid.Node.prototype.onResize=function(){if(this.parent&&this.parent.onResize)this.parent.onResize()};
links.TreeGrid.Frame=function(a,b){this.options=b;this.container=a;this.dom={};this.frameHeight=this.frameWidth=0;this.grid=void 0;this.eventParams={};this.selection=[];this.left=this.top=0;this.window={left:0,top:0,height:0,width:0};this.repaint()};links.TreeGrid.Frame.prototype=new links.TreeGrid.Node;links.TreeGrid.Frame.prototype.trigger=function(a,b){if(this.treegrid)this.treegrid.trigger(a,b);else throw"Error: cannot trigger an event because treegrid is missing";};
links.TreeGrid.Frame.prototype.getContainer=function(){return this.dom.itemFrame};links.TreeGrid.Frame.prototype.getTreeGrid=function(){return this.treegrid};links.TreeGrid.Frame.prototype.setTreeGrid=function(a){this.treegrid=a};links.TreeGrid.Frame.prototype.setGrid=function(a){this.grid&&(this.grid.hide(),delete this.grid);this.grid=a;this.grid.setParent(this);this.gridHeight=this.grid.getHeight();this.update();this.repaint()};
links.TreeGrid.Frame.prototype.getAbsTop=function(){return this.verticalScroll?-this.verticalScroll.get():0};links.TreeGrid.Frame.prototype.onResize=function(){this.repaint();for(var a=0;this.reflow()&&a<10;)this.update(),this.repaint(),a++;if(a>=10)try{console.log("Warning: maximum number of loops exceeded")}catch(b){}};links.TreeGrid.Frame.prototype.onRangeChange=function(){this._updateVisibleWindow();this.update();this.repaint();for(this.reflow();this.reflow();)this.repaint()};
links.TreeGrid.Frame.prototype.getVisibleWindow=function(){return this.window};links.TreeGrid.Frame.prototype.update=function(){this.grid&&this.grid.update()};links.TreeGrid.Frame.prototype._updateVisibleWindow=function(){var a=this.grid,b=this.frameHeight,c=this.frameWidth,d=a?a.getTop():0,a=a?a.getHeight():0,f=this.verticalScroll?this.verticalScroll.get():0;this.top=a>0&&b>0&&f>0?(d+a-b)/(a-b)*f:0;this.window={left:this.left,top:this.top,height:b,width:c}};
links.TreeGrid.Frame.prototype.reflow=function(){var a=!1,b=this.dom,c=this.grid;c&&(c=c.reflow(),a=a||c);c=b.mainFrame?b.mainFrame.clientHeight:0;b=b.mainFrame?b.mainFrame.clientWidth:0;a=(a=a||this.frameHeight!=c)||this.frameWidth!=b;this.frameHeight=c;this.frameWidth=b;a&&(this.verticalScroll.setInterval(0,this.gridHeight-c),this._updateVisibleWindow());this.verticalScroll.reflow();return a};links.TreeGrid.Frame.prototype.updateHeight=function(a,b){a==this.grid&&(this.gridHeight+=b)};
links.TreeGrid.Frame.prototype.repaint=function(){this._repaintFrame();this._repaintScrollbars();this._repaintGrid()};
links.TreeGrid.Frame.prototype._repaintFrame=function(){var a=this,b=this.dom,c=this.options,d=b.mainFrame;if(!d){d=document.createElement("DIV");d.className="treegrid-frame";d.style.position="relative";d.style.overflow="hidden";d.style.left="0px";d.style.top="0px";this.container.appendChild(d);b.mainFrame=d;links.TreeGrid.addEventListener(d,"mousedown",function(b){a.onMouseDown(b)});links.TreeGrid.addEventListener(d,"mousewheel",function(b){a.onMouseWheel(b)});links.TreeGrid.addEventListener(d,"touchstart",
function(b){a.onTouchStart(b)});var f=document.createElement("div");f.innerHTML="1 item";f.className="treegrid-drag-image";this.dom.dragImage=f;links.dnd.makeDraggable(d,{dragImage:f,dragImageOffsetX:10,dragImageOffsetY:-10,dragStart:function(b){return a.onDragStart(b)},dragEnd:function(b){return a.onDragEnd(b)}})}d.style.width=c.width||"100%";d.style.height=c.height||"100%";c=b.itemFrame;if(!c)c=document.createElement("DIV"),c.style.position="absolute",c.style.left="0px",c.style.top="0px",c.style.width=
"100%",c.style.height="0px",b.mainFrame.appendChild(c),b.itemFrame=c};links.TreeGrid.Frame.prototype._repaintGrid=function(){this.grid&&this.grid.repaint()};
links.TreeGrid.Frame.prototype._repaintScrollbars=function(){var a=this.dom,b=a.scrollContainer;if(!b){b=document.createElement("div");b.style.position="absolute";b.style.zIndex=9999;b.style.right="0px";b.style.top="0px";b.style.height="100%";b.style.width="16px";a.mainFrame.appendChild(b);a.scrollContainer=b;var c=this;verticalScroll=new links.TreeGrid.VerticalScroll(b);verticalScroll.addOnChangeHandler(function(){c.onRangeChange()});this.verticalScroll=verticalScroll}this.verticalScroll.redraw()};
links.TreeGrid.isArray=function(a){return a instanceof Array?!0:Object.prototype.toString.call(a)==="[object Array]"};
links.TreeGrid.Grid=function(a,b){this.setData(a);this.dom={};this.options={items:{defaultHeight:24,minHeight:24}};b&&links.TreeGrid.extend(this.options,b);this.columns=[];this.itemsHeight=0;this.items=[];this.itemCount=void 0;this.visibleItems=[];this.expandedItems=[];this.headerHeight=this.iconsWidth=0;this.header=new links.TreeGrid.Header({options:this.options});this.header.setParent(this);this.errorHeight=this.emptyHeight=this.loadingHeight=0;this.height=this.options.items.defaultHeight;this.dropAreas=
[];this.dropAreaHeight=this.options.dropAreaHeight;this.limit=this.offset=0};links.TreeGrid.Grid.prototype=new links.TreeGrid.Node;
links.TreeGrid.Grid.prototype.update=function(){var a={offset:this.offset,limit:this.limit},a=this._getRangeFromWindow(this.getVisibleWindow(),a);this.offset=a.offset;this.limit=a.limit;for(var b=this,c=this.offset,d=this.limit,a=links.TreeGrid.mergeArray(this.visibleItems,this.expandedItems),f=0,e=a.length;f<e;f++){var g=a[f];g&&g.update()}this._getChanges(c,d,function(){b.error=void 0;b._updateItems(c,d)},function(a){b.error=a})};
links.TreeGrid.Grid.prototype.updateHeight=function(a,b){var c=-1;a instanceof links.TreeGrid.Header?(this.headerHeight+=b,c=-1):a instanceof links.TreeGrid.Item&&(this.itemsHeight+=b,c=this.items.indexOf(a));var d=this.items;c+=1;for(var f=d.length;c<f;c++){var e=d[c];e&&(e.top+=b)}};
links.TreeGrid.Grid.prototype.onDrop=function(a){var b=JSON.parse(a.dataTransfer.getData("text"));if(this.dataConnector){var c=function(){},b=[b.item];a.dataTransfer.dropEffect=="move"?this.dataConnector.appendItems(b,c,c):a.dataTransfer.dropEffect=="copy"&&this.dataConnector.appendItems(b,c,c)}else console.log("dropped but do nothing",a.dataTransfer.dropEffect);links.TreeGrid.preventDefault(a)};
links.TreeGrid.mergeArray=function(a,b){for(var c=a.slice(0),d=0,f=b.length;d<f;d++){var e=b[d];a.indexOf(e)==-1&&c.push(e)}return c};
links.TreeGrid.Grid.prototype.reflow=function(){var a=!1,b=this.visibleItems;if(this.header)var c=this.header.reflow(),a=a||c;for(var d=links.TreeGrid.mergeArray(this.visibleItems,this.expandedItems),c=0,f=d.length;c<f;c++){var e=d[c];if(e)var g=e.reflow(),a=a||g}d=this.dropAreas;c=0;for(f=d.length;c<f;c++)d[c].reflow();for(var h=this.header.getFieldWidths(),d=this.columns,g=this.options.indentationWidth,c=0,f=h.length;c<f;c++)if(e=d[c],!e.fixedWidth){var j=h[c]+g;if(j>e.width)e.width=j,a=!0}c=0;
for(f=b.length;c<f;c++)for(var e=b[c],h=e.getFieldWidths(),i=0,k=d.length;i<k;i++)if(e=d[i],!e.fixedWidth&&(j=h[i]+g,j>e.width))e.width=j,a=!0;if(this.isVisible()){c=h=0;for(f=b.length;c<f;c++)e=b[c],j=e.getIconsWidth(),h=Math.max(j,h);this.iconsWidth!=h&&(a=!0);this.iconsWidth=h}b=g+this.iconsWidth;c=0;for(f=d.length;c<f;c++)e=d[c],e.left=b,b+=e.width;j=0;d&&d.length&&(b=d[d.length-1],j=b.left+b.width);a=a||j!=this.width;this.width=j;if(this.loading){if(this.dom.loading)this.loadingHeight=this.dom.loading.clientHeight}else this.loadingHeight=
0;if(this.error){if(this.dom.error)this.errorHeight=this.dom.error.clientHeight}else this.errorHeight=0;if(this.itemCount==0){if(this.dom.empty)this.emptyHeight=this.dom.empty.clientHeight}else this.emptyHeight=0;b=0;b+=this.headerHeight;b+=this.itemsHeight;b+=this.loadingHeight;b+=this.emptyHeight;if(b==0)b=this.options.items.defaultHeight;if(c=b-this.height)a=!0,this.height=b,this.onUpdateHeight(c);return a};
links.TreeGrid.Grid.prototype.repaint=function(){this._repaintLoading();this._repaintEmpty();this._repaintError();this._repaintHeader();this._repaintItems();window.count=window.count?window.count+1:1};
links.TreeGrid.Grid.prototype._repaintLoading=function(){if(this.isVisible()&&this.itemCount==void 0&&!this.error){var a=this.dom.loadingIcon;if(!a)a=document.createElement("DIV"),a.className="treegrid-loading-icon",a.style.position="absolute",a.title="refreshing...",this.getContainer().appendChild(a),this.dom.loadingIcon=a;a.style.top=Math.max(this.getAbsTop(),0)+"px";a.style.left=this.getAbsLeft()+"px"}else if(this.dom.loadingIcon)this.dom.loadingIcon.parentNode.removeChild(this.dom.loadingIcon),
this.dom.loadingIcon=void 0;if(this.isVisible()&&!this.error&&this.itemCount==void 0){a=this.dom.loadingText;if(!a)a=document.createElement("div"),a.className="treegrid-loading",a.style.position="absolute",a.appendChild(document.createTextNode("loading...")),this.getContainer().appendChild(a),this.dom.loadingText=a;a.style.top=Math.max(this.getAbsTop(),0)+"px";a.style.left=this.getAbsLeft()+this.options.indentationWidth+"px"}else if(this.dom.loadingText)delete this.loadingHeight,this.dom.loadingText.parentNode.removeChild(this.dom.loadingText),
this.dom.loadingText=void 0};
links.TreeGrid.Grid.prototype._repaintEmpty=function(){var a=this.dom;if(this.itemCount==0&&this.isVisible()){var b=a.empty;if(!b){b=document.createElement("div");b.className="treegrid-loading";b.style.position="absolute";b.appendChild(document.createTextNode("(empty)"));this.getContainer().appendChild(b);a.empty=b;var c=this.parent;(a=c.dataConnector?c.dataConnector.getOptions().dataTransfer:void 0)&&links.dnd.makeDroppable(b,{dropEffect:a.dropEffect,drop:function(a){c.onDrop(a)},dragEnter:function(a){c.onDragEnter(a)},
dragOver:function(a){c.onDragOver(a)},dragLeave:function(a){c.onDragLeave(a)}})}b.style.top=Math.max(this.getAbsTop(),0)+"px";b.style.left=this.getAbsLeft()+this.options.indentationWidth+"px";b.style.width=this.parent.width-2*this.options.indentationWidth+"px"}else a.empty&&(links.dnd.removeDroppable(b),a.empty.parentNode.removeChild(a.empty),delete this.dom.empty)};
links.TreeGrid.Grid.prototype._repaintError=function(){var a=this.dom;if(this.isVisible()&&this.error){var b=a.error;if(!b)b=document.createElement("div"),b.className="treegrid-error",b.style.position="absolute",b.appendChild(document.createTextNode("Error: "+links.TreeGrid.Grid._errorToString(this.error))),this.getContainer().appendChild(b),a.error=b;b.style.top=Math.max(this.getAbsTop(),0)+"px";b.style.left=this.getAbsLeft()+this.options.indentationWidth+"px"}else if(a.error)a.error.parentNode.removeChild(a.error),
a.error=void 0;if(this.isVisible()&&this.error&&!this.loading){a=this.dom.errorIcon;if(!a)a=document.createElement("DIV"),a.className="treegrid-error-icon",a.style.position="absolute",a.title=this.error,this.getContainer().appendChild(a),this.dom.errorIcon=a;b=this.getAbsLeft();a.style.top=Math.max(this.getAbsTop(),0)+"px";a.style.left=b+"px";a.style.zIndex=b+1}else if(this.dom.errorIcon)this.dom.errorIcon.parentNode.removeChild(this.dom.errorIcon),this.dom.errorIcon=void 0};
links.TreeGrid.Grid.prototype.getColumnsFromFields=function(a){var b=[];if(a){var c=0,d;for(d in a)if(a.hasOwnProperty(d)){var f=a[d];d.charAt(0)!="_"&&!links.TreeGrid.isArray(f)&&!(f instanceof links.DataConnector)&&(b[c]={name:d},c++)}}return b};
links.TreeGrid.Grid.prototype.setColumns=function(a){for(var b=[],c=!1,d=0,f=a.length;d<f;d++){var e=this.columns[d],g=a[d];e||(c=!0);if(!c)for(var h in g)if(e[h]!=g[h]){c=!0;break}if(!c)for(h in e)if(h!="width"&&h!="left"&&e[h]!=g[h]){c=!0;break}var j={name:"",width:0,left:0};if(!c&&e){if(e.width!=void 0)j.width=e.width;if(e.left!=void 0)j.left=e.left}j.fixedWidth=g.width!=void 0;for(h in g)j[h]=g[h];this.columns[d]=j;b[d]=j}this.columns.length!=a.length&&(c=!0);if(c){this.columns.splice(0,this.columns.length);
for(d=0;d<b.length;d++)this.columns.push(b[d])}};
links.TreeGrid.Grid.prototype.setData=function(a){if(a!=this.data){if(links.TreeGrid.isArray(a))a=new links.DataTable(a);else if(!(a instanceof links.DataConnector))throw"Error: no valid data. JSON Array or DataConnector expected.";if(this.dataConnector&&this.eventListener){this.dataConnector.removeEventListener(this.eventListener);this.dataConnector=this.eventListener=void 0;for(var b=this.items,c=0,d=this.items.length;c<d;c++){var f=b[c];if(f)f.data=void 0}}var e=this;this.eventListener=function(a){a==
"change"&&e.update()};this.dataConnector=a;this.dataConnector.addEventListener(this.eventListener);this.showHeader=this.dataConnector&&this.dataConnector.options.showHeader!=void 0?this.dataConnector.options.showHeader:!0}};links.TreeGrid.Grid.prototype._removeItem=function(a){var b=this.items,c=b.indexOf(a);if(c!=-1){if(a.expanded)a.onExpand();var d=this.visibleItems.indexOf(a);d!=-1&&this.visibleItems.splice(d,1);d=a.getHeight();this.updateHeight(a,-d);a.hide();b.splice(c,1);this.itemCount--}};
links.TreeGrid.Grid.prototype._updateHeader=function(a){this.header.setFields(a)};
links.TreeGrid.Grid.prototype._getChanges=function(a,b,c,d){for(var f=this,e=[],g=[],h=a,j=a+b;h<j;h++){var i=this.getItem(h);e.push(i.data);g.push(h)}h=0;for(j=g.length;h<j;h++)this.items[g[h]].updating=!0;this.dataConnector.getChanges(a,b,e,function(d){var g=d.items||[],h=e.length<b||g.length>0,i=d.totalItems!==f.itemCount;i&&f.setItemCount(d.totalItems);for(var d=a,j=a+b;d<j;d++){var o=f.getItem(d);o.updating=!1;if(!o.data||g.indexOf(o.data)!=-1)o.dirty=!0}if(i||h)f.onResize();c&&c(g)},function(c){for(var e=
a,g=a+b;e<g;e++){var h=f.getItem(e);h.error=c;h.updating=!1;h.dirty=!0}f.onResize();d&&d(c)})};
links.TreeGrid.Grid.prototype._updateItems=function(a,b,c,d){for(var f=this,e=this.getItem(a);b>0&&(e.loading||!e.dirty&&e.data);)a++,b--,e=this.getItem(a);for(e=this.getItem(a+b-1);b>0&&(e.loading||!e.dirty&&e.data);)b--,e=this.getItem(a+b-1);for(var g=a,h=a+b;g<h;g++)if(e=this.getItem(g),e.error||e.dirty||!e.data)e.loading=!0,e.dirty=!0;e=function(d){for(var d=d.items,e=a,g=a+b;e<g;e++){var h=f.getItem(e);h.loading=!1;h.dirty=!1}d.length&&(e=f.dataConnector.getOptions().columns||f.getColumnsFromFields(d[0]),
f.setColumns(e),f._updateHeader(f.columns));e=0;for(g=d.length;e<g;e++){var p=d[e];if(p)h=f.getItem(a+e),h.data=p,h.setFields(p,f.columns),h.error=void 0}f.onResize();c&&c()};g=function(c){for(var e=a,g=a+b;e<g;e++){var h=f.getItem(e);h.loading=!1;h.dirty=!0;h.error=c}f.onResize();d&&d(c)};b>0||this.totalItems===void 0?(this.repaint(),this.dataConnector.getItems(a,b,e,g)):c&&c()};
links.TreeGrid.Grid.prototype._repaintHeader=function(){this.header.setVisible(this.showHeader&&this.itemCount!=void 0&&this.itemCount>0);this.header.repaint()};
links.TreeGrid.Grid.prototype._repaintItems=function(){for(var a=this.visibleItems,b=this.isVisible(),a=this.visibleItems,c=0;c<a.length;){var d=a[c];if(d.index<this.offset||d.index>=this.offset+this.limit||!b)d.hide(),d=a.indexOf(d),d!=-1&&(a.splice(d,1),c--);c++}c=this.offset;b=Math.min(this.offset+this.limit,this.itemCount||0);if(this.isVisible())for(;c<b;c++)d=this.getItem(c),d.setVisible(!0),a.indexOf(d)==-1&&a.push(d);for(c=0;c<a.length;c++)d=a[c],d.repaint()};
links.TreeGrid.Grid.prototype._repaintDropAreas=function(){var a="none";if(this.dataConnector&&this.dataConnector.options&&this.dataConnector.options.dataTransfer&&this.dataConnector.options.dataTransfer.dropEffect)a=this.dataConnector.options.dataTransfer.dropEffect;if(a!="none"&&this.isVisible()){var b=this.offset,a=Math.min(this.offset+this.limit,this.itemCount||0),c=this.dropAreas,d=this.dropAreaHeight;this.getContainer();for(var f=this.limit-c.length,e=-f,g=0;g<f;g++){var h=new links.TreeGrid.DropArea({dataConnector:this.dataConnector,
item:this.getItem(this.offset+g),height:d});h.setParent(this);c.push(h)}for(g=0;g<e;g++)h=c.shift(),h.hide();for(g=b;g<a;g++)b=this.getItem(g),h=c[g-this.offset],h.setTop(b.top-d),h.item=b,h.repaint()}else for(c=this.dropAreas;c.length>0;)h=c.shift(),h.hide()};links.TreeGrid.Header=function(a){if(a)this.height=a.height||0,this.options=a.options;this.fieldsHeight=0;this.dom={};this.columns=void 0};links.TreeGrid.Header.prototype=new links.TreeGrid.Node;
links.TreeGrid.Header.prototype.clearFields=function(){this.columns=void 0;this.fieldsHeight=0};
links.TreeGrid.Header.prototype.repaint=function(){if(this.isVisible()&&this.columns){var a=this.columns;if(a!=this.prevColumns)this.hide(),this.prevColumns=a;var b=this.dom.header;if(!b&&(b=document.createElement("DIV"),b.treeGridType="header",b.className="treegrid-header",b.style.position="absolute",b.style.zIndex=1+this.getAbsLeft(),this.getContainer().appendChild(b),this.dom.header=b,this.dom.fields=[],this.columns))for(var a=this.columns,c=0,d=a.length;c<d;c++)if(!this.dom.fields[c]){var a=this.columns[c],
f=document.createElement("DIV");f.className="treegrid-header-field";f.style.position="absolute";f.style.top="0px";f.innerHTML=a.text||a.name||"";f.title=a.title||"";b.appendChild(f);this.dom.fields[c]=f}c=Math.max(this.getAbsTop(),0);b.style.top=c+"px";b.style.left=this.getAbsLeft()+"px";b.style.height=this.height+"px";b.style.width=this.width+"px";b=this.dom.fields;a=this.columns;c=0;for(d=b.length;c<d;c++)b[c].style.left=a[c].left+"px"}else if(this.dom.header)this.dom.header.parentNode.removeChild(this.dom.header),
this.dom.header=void 0,this.dom.fields=void 0};links.TreeGrid.Header.prototype.reflow=function(){var a=!1,b=this.dom?this.dom.fields:void 0,c=b?b.length:0,d=this.options.items.minHeight;if(b){for(var f=0;f<c;f++)b[f]&&(d=Math.max(d,b[f].clientHeight));this.fieldsHeight=d}else if(!this.columns)this.fieldsHeight=0;this.width=this.getVisibleWindow().width-this.getAbsLeft();b=0;b+=this.fieldsHeight;if(c=b-this.height)a=!0,this.height=b,this.onUpdateHeight(c);return a};
links.TreeGrid.Header.prototype.setFields=function(a){if(a)this.columns=a};links.TreeGrid.Header.prototype.getFieldWidths=function(){var a=[];if(this.dom.fields)for(var b=this.dom.fields,c=0,d=b.length;c<d;c++)a[c]=b[c].clientWidth;return a};
links.TreeGrid.Grid.prototype.setItemCount=function(a){var b=this.options.items.defaultHeight,c=a-(this.itemCount||0);c>0&&(this.itemsHeight+=(b+this.dropAreaHeight)*c);if(c<0){for(var c=this.itemCount,d=this.items,f=a;f<c;f++){var e=d[f];e&&(e.hide(),delete d[f]);this.itemsHeight-=(e?e.getHeight():b)+this.dropAreaHeight}a==0&&this.header.clearFields()}this.itemCount=a||0};links.TreeGrid.Grid.prototype.registerExpandedItem=function(a){this.expandedItems.indexOf(a)==-1&&this.expandedItems.push(a)};
links.TreeGrid.Grid.prototype.unregisterExpandedItem=function(a){a=this.expandedItems.indexOf(a);a!=-1&&this.expandedItems.splice(a,1)};links.TreeGrid.Grid.prototype.getItemCount=function(){return this.itemCount};links.TreeGrid.Grid.prototype.getItem=function(a){var b=this.items[a];b||(b=new links.TreeGrid.Item({options:this.options,index:a,top:this._calculateItemTop(a),height:this.options.items.defaultHeight}),b.setParent(this),this.items[a]=b);return b};
links.TreeGrid.Grid.prototype._calculateItemTop=function(a){for(var b=this.items,c=this.options.items.defaultHeight,d=0,f=void 0,e=a-1;e>=0;e--)if((f=b[e])&&f.top){d+=f.top+f.height;break}else d+=c;return f!=void 0?d+this.dropAreaHeight:this.headerHeight+c*a+this.dropAreaHeight*(a+1)};
links.TreeGrid.Item=function(a){if(a)this.options=a.options,this.index=a.index||0,this.top=a.top||0;this.height=this.options.items.defaultHeight;this.fields=this.data=void 0;this.fieldsHeight=0;this.grid=void 0;this.gridHeight=0;this.loading=this.dirty=!1;this.loadingHeight=0;this.error=void 0;this.errorheight=0;this.dataTransfer={};this.dom={}};links.TreeGrid.Item.prototype=new links.TreeGrid.Node;
links.TreeGrid.eval=function(a,b){var c=typeof a;if(c=="function")return a.call(b);else if(c=="string"){c=links.TreeGrid.evalHistory;if(!c)c={},links.TreeGrid.evalHistory=c;var d=c[a];d||(d=eval("f=("+a+");"),c[a]=d);return d.call(b)}else throw Error("Function must be of type function or string");};
links.TreeGrid.Item.prototype.setFields=function(a,b){if(a&&b){for(var c=[],d=0,f=b.length;d<f;d++){var e=b[d];c[d]=e.format?links.TreeGrid.eval(e.format,a)||"":a[e.name]||""}this.fields=c;this.columns=b;this.icons=a._icons;this.actions=a._actions;var c=[],g;for(g in a)if(a.hasOwnProperty(g)&&g.charAt(0)!="_"&&(d=a[g],links.TreeGrid.isArray(d)?c.push({name:g,data:new links.DataTable(d)}):d instanceof links.DataConnector&&c.push({name:g,data:d})),g=="_childs")try{console.log("WARNING: special field _childs encountered. This field is no longer in use for subgrids, and is now a regular hidden field. Use a fieldname without underscore instead for subgrids.")}catch(h){}g=
void 0;c.length==1?g=c[0].data:c.length>1&&(g=new links.DataTable(c,{showHeader:!1}));if(g)this.dataConnector=g,this.grid&&(this.grid.setData(this.dataConnector),this.grid.update());else{this.dataConnector&&delete this.dataConnector;if(this.grid)this.grid.hide(),this.gridHeight=0,delete this.grid;if(this.expanded)this.expanded=!1,this.parent.unregisterExpandedItem(this)}}};
links.TreeGrid.Item.prototype.getFieldWidths=function(){var a=[];if(this.dom.fields)for(var b=this.dom.fields,c=0,d=this.columns.length;c<d;c++)a[c]=b[c]?b[c].clientWidth:0;return a};links.TreeGrid.Item.prototype.getIconsWidth=function(){return this.dom.icons?this.dom.icons.clientWidth:0};links.TreeGrid.Item.prototype.updateHeight=function(a,b){a==this.grid&&(this.gridHeight+=b)};
links.TreeGrid.Item.prototype.onEvent=function(a){var b={items:[this.data]};links.events.trigger(this.getTreeGrid(),a,b);var c=this.parent.dataConnector;c&&c._onEvent(a,b)};
links.TreeGrid.Item.prototype.onExpand=function(){if(this.expanded)this.dom.buttonExpand.className="treegrid-fold",this.expanded=!1,this.parent.unregisterExpandedItem(this),this.grid&&(this.grid.setVisible(!1),this.gridHeight-=this.grid.getHeight()+this.options.padding),this.onEvent("collapse");else{this.dom.buttonExpand.className="treegrid-unfold";this.expanded=!0;this.parent.registerExpandedItem(this);if(this.dataConnector){if(!this.grid)this.grid=new links.TreeGrid.Grid(this.dataConnector,this.options),
this.grid.setParent(this),this.grid.setLeft(this.left+this.options.indentationWidth),this.grid.setTop(this.height);this.grid.setVisible(!0);this.gridHeight+=this.grid.getHeight()+this.options.padding}this.onEvent("expand")}this.onResize()};
links.TreeGrid.Item.prototype.onDragOver=function(a){if(!this.dataTransfer.dragging){var b=(a.offsetY||a.layerY)<this.fieldsHeight/2||!this.dataConnector,b=!1;this.dataTransfer.dragover=!b;this.dataTransfer.dragbefore=b;this.repaint();links.TreeGrid.preventDefault(a);return!1}};links.TreeGrid.Item.prototype.onDragEnter=function(){return this.dataTransfer.dragging?void 0:!1};
links.TreeGrid.Item.prototype.onDragLeave=function(){if(!this.dataTransfer.dragging)return this.dataTransfer.dragover=!1,this.dataTransfer.dragbefore=!1,this.repaint(),!1};
links.TreeGrid.Item.prototype.onDrop=function(a){var b=a.dataTransfer.getData("items");this.dataTransfer.dragover=!1;this.dataTransfer.dragbefore=!1;this.repaint();if(this.dataConnector){for(var c=this,d=function(){if(c.expanded)c.onResize();else c.onExpand()},f=d,e=0;e<b.length;){for(var g=this;g&&g!=b[e];)g=g.parent;g==b[e]?b.splice(e,1):e++}g=[];for(e=0;e<b.length;e++)g.push(b[e].data);this.dataConnector.appendItems(g,d,f)}else if(this.parent&&this.parent.dataConnector&&a.dataTransfer.dropEffect==
"link"){for(var g=this.data,d=function(){},f=function(a){console.log(a)},h=[],e=0;e<b.length;e++)h.push(b[e].data);this.parent.dataConnector.linkItems(h,g,d,f)}else console.log("dropped but do nothing",a.dataTransfer.dropEffect);links.TreeGrid.preventDefault(a)};links.TreeGrid.Item.prototype.repaint=function(){this._repaintError();this._repaintLoading();this._repaintFields();this._repaintGrid()};links.TreeGrid.Item.prototype.update=function(){this.grid&&this.expanded&&this.grid.update()};
links.TreeGrid.Item.prototype.reflow=function(){var a=!1;if(this.grid&&this.expanded)var b=this.grid.reflow(),a=a||b;this.width=this.getVisibleWindow().width-this.getAbsLeft();if(this.isVisible()){var b=this.options.items.minHeight,c=this.dom.fields,d=this.dom.actions,f=this.dom.icons,e=this.dom.expandButton,g=c?c.length:0;if(f){var h=f.clientWidth;h!=this.iconsWidth&&(a=!0);this.iconsWidth=h}if(c||d||f||e||d){for(h=0;h<g;h++)c[h]&&(b=Math.max(b,c[h].clientHeight));d&&(b=Math.max(b,d.clientHeight));
f&&(b=Math.max(b,f.clientHeight));e&&(b=Math.max(b,e.clientHeight));this.fieldsHeight=b}}if(this.loading){if(this.dom.loading)this.loadingHeight=this.dom.loading.clientHeight}else this.loadingHeight=0;if(this.error){if(this.dom.error)this.errorHeight=this.dom.error.clientHeight}else this.errorHeight=0;b=0;b+=this.fieldsHeight;b+=this.loadingHeight;b+=this.errorHeight;b+=this.gridHeight;if(b==0)b=this.options.items.defaultHeight;if(c=b-this.height)a=!0,this.height=b,this.onUpdateHeight(c);return a};
links.TreeGrid.Grid.prototype._getRangeFromWindow=function(a,b){var c=this.options.items.defaultHeight,d=this.itemCount!=void 0?this.itemCount:Math.ceil(a.height/c),f=-this.getAbsTop()+this.header.getHeight(),e=f+a.height-this.header.getHeight(),g=b?b.offset:0,h=0,j,i,k;i=(j=this.items[g])?j.top:this._calculateItemTop(g);j=j?j.getHeight():c;for(k=i+j;g<d-1&&k<f;)g++,j=this.items[g],i=k+this.dropAreaHeight,j=j?j.getHeight():c,k=i+j;for(;g>0&&i>f;)g--,j=(j=this.items[g])?j.getHeight():c,k=i,i=i-j-this.dropAreaHeight;
for(;g+h<d-1&&i<e;)h++,j=this.items[g+h],i=k+this.dropAreaHeight,j=j?j.getHeight():c,k=i+j;i<e&&k>f&&g+h<d&&h++;return{offset:g,limit:h}};
links.TreeGrid.Item.prototype._repaintFields=function(){var a;if(this.isVisible()&&this.fields){var b=this.fields;if(b!=this.prevFields)this.dom.frame&&(this.dom.frame.parentNode.removeChild(this.dom.frame),delete this.dom.frame),this.prevFields=b;var c=this.dom.frame;if(!c){c=document.createElement("DIV");c.className="treegrid-item";c.style.position="absolute";c.item=this;c.treeGridType="item";this.dom.frame=c;if(this.dataConnector){var d=document.createElement("button");d.treeGridType="expand";
d.className=this.expanded?"treegrid-unfold":"treegrid-fold";d.style.position="absolute";d.grid=this;d.node=this;d.index=this.index;c.appendChild(d);this.dom.buttonExpand=d}if(a=this.icons){b=document.createElement("DIV");b.className="treegrid-icons";b.style.position="absolute";b.style.top="0px";for(var d=0,f=a.length;d<f;d++){var e=a[d];if(e&&e.image){var g=document.createElement("img");g.className="treegrid-icon";g.src=e.image;g.title=e.title?e.title:"";g.style.width=e.width?e.width:"";g.style.height=
e.height?e.height:"";b.appendChild(g)}}c.appendChild(b);this.dom.icons=b}e=[];this.dom.fields=e;b=this.fields;d=0;for(f=b.length;d<f;d++){a=b[d];g=document.createElement("DIV");g.className="treegrid-item-field";g.style.position="absolute";g.style.top="0px";var h=this.columns[d];if(h.fixedWidth)g.style.width=h.width+"px";g.innerHTML=a;c.appendChild(g);e.push(g)}if(this.actions){a=this.actions;b=document.createElement("DIV");this.dom.actions=b;b.style.position="absolute";b.className="treegrid-actions";
b.style.top="0px";b.style.right="24px";d=0;for(f=a.length;d<f;d++)if(e=a[d],e.event)e.image?(g=document.createElement("INPUT"),g.treeGridType="action",g.type="image",g.className="treegrid-action-image",g.title=e.title||"",g.src=e.image):(g=document.createElement("A"),g.treeGridType="action",g.className="treegrid-action-link",g.href="#",g.title=e.title||"",g.innerHTML=e.text?e.text:e.event),g.event=e.event,g.item=this,b.appendChild(g);c.appendChild(b)}var j=this;if(d=this.dataConnector?this.dataConnector.getOptions().dataTransfer:
void 0){if(d.dropEffect!=void 0&&d.dropEffect!="none")this.dataTransfer.dropEffect=d.dropEffect,links.dnd.makeDroppable(c,{dropEffect:d.dropEffect,drop:function(a){j.onDrop(a)},dragEnter:function(a){j.onDragEnter(a)},dragOver:function(a){j.onDragOver(a)},dragLeave:function(a){j.onDragLeave(a)}})}else if(this.parent&&this.parent.dataConnector&&(d=this.parent.dataConnector.getOptions().dataTransfer)&&d.dropEffect=="link")this.dataTransfer.dropEffect=d.dropEffect,links.dnd.makeDroppable(c,{dropEffect:d.dropEffect,
drop:function(a){j.onDrop(a)},dragEnter:function(a){j.onDragEnter(a)},dragOver:function(a){j.onDragOver(a)},dragLeave:function(a){j.onDragLeave(a)}})}c.parentNode||this.getContainer().appendChild(c);c.style.top=this.getAbsTop()+"px";c.style.left=this.getAbsLeft()+"px";c.style.height=this.fieldsHeight+"px";c.style.width=this.width-2+"px";if(b=this.dom.icons)b.style.left=this.options.indentationWidth+"px";if(e=this.dom.fields){d=0;for(f=this.columns.length;d<f;d++)if(h=this.columns[d],g=e[d])g.style.left=
h.left+"px"}if(this.dom.buttonExpand)this.dom.buttonExpand.style.visibility=this.error==void 0?"visible":"hidden";d="treegrid-item";this.selected||this.dataTransfer.dragging?d+=" treegrid-item-selected":this.dataTransfer.dragover?d+=" treegrid-item-dragover":this.dataTransfer.dragbefore&&(d+=" treegrid-item-dragbefore");this.dirty&&(d+=" treegrid-item-dirty");c.className=d}else if(links.dnd.removeDraggable(this.dom.frame),links.dnd.removeDroppable(this.dom.frame),this.dom.frame&&this.dom.frame.parentNode&&
this.dom.frame.parentNode.removeChild(this.dom.frame),this.dom.frame)this.dom={}};links.TreeGrid.Item.prototype._repaintGrid=function(){this.grid&&this.grid.repaint()};
links.TreeGrid.Item.prototype._repaintLoading=function(){if(this.isVisible()&&this.loading&&(!this.fields||this.error||this.dirty)){var a=this.dom.loadingIcon;if(!a)a=document.createElement("DIV"),a.className="treegrid-loading-icon",a.style.position="absolute",a.title="loading...",this.getContainer().appendChild(a),this.dom.loadingIcon=a;a.style.top=this.getAbsTop()+"px";a.style.left=this.getAbsLeft()+"px"}else this.dom.loadingIcon&&(this.dom.loadingIcon.parentNode.removeChild(this.dom.loadingIcon),
delete this.dom.loadingIcon);if(this.isVisible()&&this.loading&&!this.fields&&!this.error){a=this.dom.loadingText;if(!a)a=document.createElement("DIV"),a.style.position="absolute",a.appendChild(document.createTextNode("loading...")),a.className="treegrid-loading",this.getContainer().appendChild(a),this.dom.loadingText=a;a.style.top=this.getAbsTop()+"px";a.style.left=this.getAbsLeft()+this.options.indentationWidth+"px";a.style.height=this.height+"px"}else this.dom.loadingText&&(this.dom.loadingText.parentNode.removeChild(this.dom.loadingText),
delete this.dom.loadingText)};
links.TreeGrid.Item.prototype._repaintError=function(){if(this.isVisible()&&this.error&&!this.fields){var a=this.dom.error;if(!a)a=document.createElement("DIV"),a.style.position="absolute",a.appendChild(document.createTextNode("Error: "+links.TreeGrid.Grid._errorToString(this.error))),a.className="treegrid-error",this.getContainer().appendChild(a),this.dom.error=a;a.style.top=this.getAbsTop()+"px";a.style.left=this.getAbsLeft()+this.options.indentationWidth+"px"}else this.dom.error&&(this.dom.error.parentNode.removeChild(this.dom.error),
delete this.dom.error);if(this.isVisible()&&this.error&&!this.loading){a=this.dom.errorIcon;if(!a)a=document.createElement("DIV"),a.className="treegrid-error-icon",a.style.position="absolute",a.title=this.error,this.getContainer().appendChild(a),this.dom.errorIcon=a;var b=this.getAbsLeft();a.style.top=Math.max(this.getAbsTop(),0)+"px";a.style.left=b+"px"}else if(this.dom.errorIcon)this.dom.errorIcon.parentNode.removeChild(this.dom.errorIcon),this.dom.errorIcon=void 0};
links.TreeGrid.DropArea=function(a){if(a)this.dataConnector=a.dataConnector||void 0,this.item=a.item||void 0,this.top=a.top||0,this.height=a.height||6;this.dragover=!1;this.dom={}};links.TreeGrid.DropArea.prototype=new links.TreeGrid.Node;links.TreeGrid.DropArea.prototype.reflow=function(){this.width=this.getVisibleWindow().width-this.getAbsLeft()};
links.TreeGrid.DropArea.prototype.repaint=function(){if(this.isVisible()){var a=this.dom.dropArea;if(!a){var b=this.getContainer(),a=document.createElement("DIV");a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.height=this.height+"px";b.appendChild(a);this.dom.dropArea=a;if(b=this.dataConnector?this.dataConnector.getOptions().dataTransfer:void 0){var c=this;this.dropEffect=b.dropEffect;links.TreeGrid.addEventListener(a,"dragover",function(a){return c.onDragOver(a)});links.TreeGrid.addEventListener(a,
"dragenter",function(a){return c.onDragEnter(a)});links.TreeGrid.addEventListener(a,"dragleave",function(a){return c.onDragLeave(a)});links.TreeGrid.addEventListener(a,"drop",function(a){return c.onDrop(a)})}}a.className=this.dragover?"treegrid-droparea":"";a.style.top=this.getAbsTop()+"px";a.style.left=this.getAbsLeft()+"px";a.style.width=this.width-2+"px"}else this.dom.dropArea&&(this.dom.dropArea.parentNode.removeChild(this.dom.dropArea),delete this.dom.dropArea)};
links.TreeGrid.DropArea.prototype.onDragOver=function(a){this.dragover=!0;a.dataTransfer.allowedEffect="none";a.dataTransfer.dropEffect=this.dropEffect||"none";this.repaint();links.TreeGrid.preventDefault(a);return!1};links.TreeGrid.DropArea.prototype.onDragEnter=function(a){this.dragover=!0;this.repaint();a.dataTransfer.allowedEffect="none";a.dataTransfer.dropEffect=this.dataConnector?"move":"none";return!1};
links.TreeGrid.DropArea.prototype.onDragLeave=function(){this.dragover=!1;this.repaint();return!1};links.TreeGrid.DropArea.prototype.onDrop=function(a){var b=JSON.parse(a.dataTransfer.getData("text"));this.dragover=!1;this.repaint();if(this.dataConnector){var c=this,d=function(){c.parent.onResize()};this.dataConnector.insertItemsBefore([b.item],this.item.data,d,d)}else console.log("dropped but do nothing",a.dataTransfer.dropEffect);links.TreeGrid.preventDefault(a)};
links.TreeGrid.Grid._errorToString=function(a){if(typeof a=="string")return a;else if(a instanceof Object){if(a.message&&typeof a.message=="string")return a.message;if(a.error&&typeof a.error=="string")return a.error;if(JSON)return JSON.stringify(a)}return String(a)};links.TreeGrid.VerticalScroll=function(a,b,c,d){this.container=a;this.dom={};this.value=this.max=this.min=this.height=0;this.eventParams={};this.onChangeHandlers=[];this.setInterval(b,c);this.set(d)};
links.TreeGrid.VerticalScroll.prototype.redraw=function(){var a=this.dom.background;if(!a)a=document.createElement("div"),a.className="treegrid-verticalscroll-background",a.style.width="100%",a.style.height="100%",this.container.appendChild(a),this.dom.background=a;a=this.dom.bar;if(!a){a=document.createElement("div");a.className="treegrid-verticalscroll-bar";a.style.position="absolute";a.style.left="20%";a.style.width="60%";a.style.right="20%";a.style.top="0px";a.style.height="0px";this.container.appendChild(a);
var b=this,c=this.eventParams;c._onMouseDown=function(a){b._onMouseDown(a)};links.TreeGrid.addEventListener(a,"mousedown",c._onMouseDown);this.dom.bar=a}var d=this.max-this.min;if(d>0){var f=this.height,c=Math.max(f*f/(d+f),20),d=this.value*(f-c-4)/d;a.style.height=c+"px";a.style.top=d+"px";a.style.display=""}else a.style.display="none"};links.TreeGrid.VerticalScroll.prototype.checkResize=function(){var a=this.reflow();a&&this.redraw();return a};
links.TreeGrid.VerticalScroll.prototype.reflow=function(){this.height=this.dom.background.clientHeight;return!1};links.TreeGrid.VerticalScroll.prototype.setInterval=function(a,b){this.min=a||0;this.max=b||0;if(this.max<this.min)this.max=this.min;this.set(this.value)};links.TreeGrid.VerticalScroll.prototype.set=function(a){this.value=a||this.min;if(this.value<this.min)this.value=this.min;if(this.value>this.max)this.value=this.max;this.redraw()};
links.TreeGrid.VerticalScroll.prototype.increase=function(a){var b=this.get();b+=a;this.set(b)};links.TreeGrid.VerticalScroll.prototype.get=function(){return this.value};
links.TreeGrid.VerticalScroll.prototype._onMouseDown=function(a){var b=this.eventParams,a=a||window.event;b.startMouseX=a.clientX;b.startMouseY=a.clientY;b.startValue=this.value;var c=this;if(!b._onMouseMove)b._onMouseMove=function(a){c._onMouseMove(a)},links.TreeGrid.addEventListener(document,"mousemove",b._onMouseMove);if(!b._onMouseUp)b._onMouseUp=function(a){c._onMouseUp(a)},links.TreeGrid.addEventListener(document,"mouseup",b._onMouseUp);links.TreeGrid.preventDefault(a);links.TreeGrid.stopPropagation(a)};
links.TreeGrid.VerticalScroll.prototype._onMouseMove=function(a){var b=this.eventParams,a=a||window.event;this.set(b.startValue+(a.clientY-b.startMouseY)/this.height*(this.max-this.min+this.height));this._callbackOnChangeHandlers();links.TreeGrid.preventDefault(a);links.TreeGrid.stopPropagation(a)};
links.TreeGrid.VerticalScroll.prototype._onMouseUp=function(a){var b=this.eventParams;if(b._onMouseMove)links.TreeGrid.removeEventListener(document,"mousemove",b._onMouseMove),b._onMouseMove=void 0;if(!b.onMouseUp)links.TreeGrid.removeEventListener(document,"mouseup",b._onMouseUp),b._onMouseUp=void 0;links.TreeGrid.preventDefault(a);links.TreeGrid.stopPropagation(a)};links.TreeGrid.VerticalScroll.prototype.addOnChangeHandler=function(a){this.removeOnChangeHandler(a);this.onChangeHandlers.push(a)};
links.TreeGrid.VerticalScroll.prototype.removeOnChangeHandler=function(a){this.onChangeHandlers.splice(this.onChangeHandlers.indexOf(a),1)};links.TreeGrid.VerticalScroll.prototype._callbackOnChangeHandlers=function(){for(var a=this.onChangeHandlers,b=this.value,c=0,d=a.length;c<d;c++)a[c](b)};links.DataConnector=function(a){this.options=a||{};this.eventListeners=[]};
links.DataConnector.prototype.trigger=function(a,b){links.events.trigger(this,a,b);google&&google.visualization&&google.visualization.events&&google.visualization.events.trigger(this,a,b);for(var c=this.eventListeners,d=0,f=c.length;d<f;d++)(0,c[d])(a,b)};links.DataConnector.prototype.getChanges=function(){throw"Error: method getChanges is not implemented";};links.DataConnector.prototype.getItems=function(a,b,c,d){d("Error: method getItems is not implemented")};
links.DataConnector.prototype.updateItems=function(a,b,c){c("Error: method updateItems is not implemented")};links.DataConnector.prototype.appendItems=function(a,b,c){c("Error: method appendItems is not implemented")};links.DataConnector.prototype.insertItemsBefore=function(a,b,c,d){d("Error: method insertItemsBefore is not implemented")};links.DataConnector.prototype.moveItems=function(a,b,c,d){d("Error: method moveItems is not implemented")};
links.DataConnector.prototype.removeItems=function(a,b,c){c("Error: method removeItems is not implemented")};links.DataConnector.prototype.linkItems=function(a,b,c,d){d("Error: method linkItems is not implemented")};links.DataConnector.prototype._onEvent=function(a,b){this.trigger(a,b);this.onEvent(a,b)};links.DataConnector.prototype.onEvent=function(){};links.DataConnector.prototype.setFilters=function(){errback("Error: method setFilters is not implemented")};
links.DataConnector.prototype.addEventListener=function(a){this.eventListeners.indexOf(a)==-1&&this.eventListeners.push(a)};links.DataConnector.prototype.removeEventListener=function(a){a=this.eventListeners.indexOf(a);a!=-1&&this.eventListeners.splice(a,1)};links.DataConnector.prototype.setOptions=function(a){this.options=a||{}};links.DataConnector.prototype.getOptions=function(){return this.options};links.DataTable=function(a,b){this.data=a||[];this.setOptions(b);this.filteredData=this.data};
links.DataTable.prototype=new links.DataConnector;links.DataTable.prototype.getItems=function(a,b,c){for(var d=[],f=this.filteredData,e=a,a=Math.min(a+b,f.length);e<a;e++)d.push(f[e]);c({totalItems:f.length,items:d})};links.DataTable.prototype.updateItems=function(a,b,c){for(var d=a.length,f=this.data,e=0;e<d;e++){var g=a[e],h=f.indexOf(g);if(h!=-1)f[h]=g;else{c("Cannot find item");return}}this.updateFilters();b({totalItems:this.filteredData.length,items:a});this.trigger("change",void 0)};
links.DataTable.prototype.appendItems=function(a,b){for(var c=a.length,d=0;d<c;d++)this.data.push(a[d]);this.updateFilters();b({totalItems:this.filteredData.length,items:a});this.trigger("change",void 0)};links.DataTable.prototype.insertItemsBefore=function(a,b,c,d){var f=this.data,b=f.indexOf(b);if(b==-1)d("Cannot find item");else{for(var d=a.length,e=0;e<d;e++)f.splice(b+e,0,a[e]);this.updateFilters();c({totalItems:this.filteredData.length,items:a});this.trigger("change",void 0)}};
links.DataTable.prototype.moveItems=function(a,b,c,d){b=this.data.indexOf(b);if(b==-1)d("Cannot find item");else{for(var f=a.length,e=[],g=0;g<f;g++){var h=this.data.indexOf(a[g]);if(h!=-1)e[g]=h;else{d("Cannot find item");return}}for(g=0;g<f;g++)this.data.splice(e[g],1),this.data.splice(b,0,a[g]);this.updateFilters();c({totalItems:this.filteredData.length,items:a});this.trigger("change",void 0)}};
links.DataTable.prototype.removeItems=function(a,b,c){for(var d=a.length,f=0;f<d;f++){var e=this.data.indexOf(a[f]);if(e!=-1)this.data.splice(e,1);else{c("Cannot find item");return}}this.updateFilters();b({totalItems:this.filteredData.length,items:a});this.trigger("change",void 0)};links.DataTable.prototype.getChanges=function(a,b,c,d){for(var f=[],e=this.filteredData,g=0;g<b;g++){var h=c[g];h!=e[a+g]&&f.push(h)}d({totalItems:this.filteredData.length,items:f})};
links.DataTable.prototype.update=function(){this.updateFilters();this.trigger("change",void 0)};links.DataTable.prototype.onEvent=function(){};links.DataTable.prototype.updateFilters=function(){this.filters?this.setFilters(this.filters):this.filteredData=this.data};
links.DataTable.prototype.setFilters=function(a){var b=this.data,c=[];this.filteredData=c;this.filters=a;for(var d=0,f=b.length;d<f;d++){for(var e=b[d],g=!0,h=0,j=a.length;h<j;h++){var i=a[h];if(i.field){var k=e[i.field];i.value&&k!=i.value&&(g=!1);i.startValue&&k<i.startValue&&(g=!1);i.endValue&&k>i.endValue&&(g=!1);i.values&&i.values.indexOf(k)==-1&&(g=!1)}}g&&c.push(e)}for(var n=[],h=0,j=a.length;h<j;h++)if(i=a[h],i.field&&i.order)if(b=i.order.toUpperCase(),b=="ASC"||b=="DESC")n.push({field:i.field,
direction:b=="ASC"?1:-1});else throw'Unknown order "'+b+'". Available values: "ASC", "DESC".';var p=n.length;p&&c.sort(function(a,b){for(var c=0;c<p;c++){var d=n[c],e=d.field,d=d.direction;if(a[e]==b[e]){if(c==p-1)return 0}else return a[e]>b[e]?d:-d}})};links.CouchConnector=function(a){this.url=a;this.data=[];this.updateSeq=this.filter=void 0;this.totalItems=this.blockSize=16};links.CouchConnector.prototype=new links.DataConnector;
links.CouchConnector.prototype.getItems=function(a,b,c,d){function f(a,b){for(var c=[],d=a,e=a+b;d<e;d++){var f=g[d];c.push(f?f.value:void 0)}return c}for(var e=this,g=this.data,h=!0,j=a,i=a+b;j<i;j++)if(g[j]==void 0){h=!1;break}if(h)h=f(a,b),c({totalItems:e.totalItems,items:h});else{for(var h=a%this.blockSize,k=a-h,j=(b+h)%this.blockSize,h=b+h-j+(j!=0?this.blockSize:0);g[k]&&h>0;)k++,h--;for(;g[k+h-1]&&h>0;)h--;j=void 0;for(i=k-1;i>0&&g[i]==void 0;)i--;if(g[i])j=g[i].key;var n=this.url.indexOf("?")==
-1?"?":"&";j?h=this.url+n+"skip="+(k-i)+"&limit="+h+"&startkey="+escape(JSON.stringify(j)):(h=this.url+n+"skip="+k+"&limit="+h,this.filter&&(this.filter.value!=void 0&&(h+="&key="+escape(JSON.stringify(this.filter.value))),this.filter.startValue!=void 0&&(h+="&startkey="+escape(JSON.stringify(this.filter.startValue))),this.filter.endValue!=void 0&&(h+="&endkey="+escape(JSON.stringify(this.filter.endValue)))));links.getJSONP(h,function(h){if(h.error)d(h);else{for(var j=h.rows,i=[],i=0,n=j.length;i<
n;i++)g[i+k]=j[i];e.totalItems=Math.min(e.data.length+e.blockSize,h.total_rows);i=f(a,b);c({totalItems:e.totalItems,items:i})}},d)}};links.CouchConnector.prototype._getUpdateSeq=function(a,b){var c=this.url.indexOf("_view");c==-1?b("Error: cannot get information on this view, url is no view"):(c=this.url.substring(0,c)+"_info",links.getJSONP(c,function(c){data.error?b(data):a(c.view_index.update_seq)},b))};
links.CouchConnector.prototype.getChanges=function(a,b,c,d){a=[];d({totalItems:this.totalItems||10,items:a});return a};links.CouchConnector.prototype.setFilters=function(a){if(a.length>1)throw"CouchConnector can currently only handle one filter";else if(a.length>0)this.filter=a[0]};
links.getJSONP=function(a,b,c){var d="callback"+Math.round(Math.random()*1E10),f=document.createElement("script"),e=a.indexOf("?")==-1?"?":"&";f.src=a+e+"callback="+d;f.onerror=function(){document.body.removeChild(f);delete window[d];c&&c()};f.type="text/javascript";window[d]=function(a){document.body.removeChild(f);delete window[d];b&&b(a)};document.body.appendChild(f)};
links.TreeGrid.Frame.prototype.onDragStart=function(a){var g;var e;for(var b=[],c=0;c<this.selection.length;c++){var d=this.selection[c],f=d.parent,f=(g=(e=(f=f?f.dataConnector:void 0)?f.options:void 0,f=e)?f.dataTransfer:void 0,f=g)?f.allowedEffect:void 0;f!=void 0&&f.toLowerCase()!="none"&&b.push(d)}if(b.length>0){if(c=this.dom.dragImage)d=b.length,c.innerHTML=d+" item"+(d!=1?"s":"");a.dataTransfer.setData("items",b);return!0}else return!1};
links.TreeGrid.Frame.prototype.onDragEnd=function(a){if(a.dataTransfer.dropEffect=="move")for(var b=this,a=a.dataTransfer.getData("items"),c=a.length,d=function(){c--;c==0&&(b.unselect(),b.onResize())},f=0;f<a.length;f++){var e=a[f];e.parent._removeItem(e);e.parent.dataConnector.removeItems([e.data],d,d)}this.repaint()};
links.TreeGrid.Frame.prototype.onMouseDown=function(a){var a=a||window.event,b=this.eventParams;if((a.which?a.which==1:a.button==1)||b.touchDown)b=links.TreeGrid.getTarget(a),b.treeGridType&&b.treeGridType=="expand"?(b.grid.onExpand(),links.TreeGrid.stopPropagation(a)):b.treeGridType&&b.treeGridType=="action"?(b.item.onEvent(b.event),links.TreeGrid.stopPropagation(a)):(b=links.TreeGrid.getItemFromTarget(b))?this.select(b,a.ctrlKey,a.shiftKey):this.unselect(),links.TreeGrid.preventDefault(a)};
links.TreeGrid.Frame.prototype.select=function(a,b,c){if(c){if((c=this.selection.pop())&&c.parent!=a.parent)c.unselect(),c.repaint(),c=void 0;for(c||(c=a);this.selection.length;)b=this.selection.pop(),b.unselect(),b.repaint();var b=c.parent,d=b.items.indexOf(c),c=c==a?d:b.items.indexOf(a);if(c>=d)for(;d<=c;)a=b.items[d],a.select(),a.repaint(),this.selection.unshift(a),d++;else for(;d>=c;)a=b.items[d],a.select(),a.repaint(),this.selection.unshift(a),d--}else if(b)d=this.selection.indexOf(a),d==-1?
(a.select(),a.repaint(),this.selection.push(a)):(a.unselect(),a.repaint(),this.selection.splice(d,1));else if(!a.selected){for(;this.selection.length;)b=this.selection.pop(),b.unselect(),b.repaint();a.select();a.repaint();this.selection.push(a)}this.trigger("select",{items:this.getSelection()})};links.TreeGrid.Frame.prototype.unselect=function(a){for(var b=this.selection,c=0,d=b.length;c<d;c++)b[c].unselect(),b[c].repaint();this.selection=[];a==void 0&&(a=!0);a&&this.trigger("select",{items:[]})};
links.TreeGrid.Frame.prototype.getSelection=function(){for(var a=this.selection,b=[],c=0,d=a.length;c<d;c++)b.push(a[c].data);return b};
links.TreeGrid.Frame.prototype.onTouchStart=function(a){var b=this.eventParams,c=this;if(!b.touchDown){b.startClientY=a.targetTouches[0].clientY;b.currentClientY=b.startClientY;b.previousClientY=b.startClientY;b.startScrollValue=this.verticalScroll.get();b.touchDown=!0;if(!b.onTouchMove)b.onTouchMove=function(a){c.onTouchMove(a)},links.TreeGrid.addEventListener(document,"touchmove",b.onTouchMove);if(!b.onTouchEnd)b.onTouchEnd=function(a){c.onTouchEnd(a)},links.TreeGrid.addEventListener(document,"touchend",
b.onTouchEnd)}};links.TreeGrid.Frame.prototype.onTouchMove=function(a){var b=this.eventParams,c=a.targetTouches[0].clientY;this.verticalScroll.set(b.startScrollValue-(c-b.startClientY));this.onResize();b.previousClientY=b.currentClientY;b.currentClientY=c;this.trigger("rangechange",void 0);links.TreeGrid.preventDefault(a)};
links.TreeGrid.Frame.prototype.onTouchEnd=function(a){var b=this.eventParams,c=this;b.touchDown=!1;var d=b.currentClientY-b.startClientY,f=b.currentClientY-b.previousClientY,e=function(){b.touchDown||(c.verticalScroll.set(b.startScrollValue-d),c.onRangeChange(),d+=f,f*=0.8,Math.abs(f)>1&&setTimeout(e,50))};e();this.trigger("rangechanged",void 0);b.onTouchMove&&(links.TreeGrid.removeEventListener(document,"touchmove",b.onTouchMove),delete b.onTouchMove);b.onTouchEnd&&(links.TreeGrid.removeEventListener(document,
"touchend",b.onTouchEnd),delete b.onTouchEnd);links.TreeGrid.preventDefault(a)};links.TreeGrid.Frame.prototype.onMouseWheel=function(a){if(!a)a=window.event;var b=0;a.wheelDelta?b=a.wheelDelta/120:a.detail&&(b=-a.detail/3);b&&(this.verticalScroll.increase(-b*50),this.onRangeChange(),this.trigger("rangechanged",void 0));links.TreeGrid.preventDefault(a)};
links.TreeGrid.prototype.trigger=function(a,b){links.events.trigger(this,a,b);google&&google.visualization&&google.visualization.events&&google.visualization.events.trigger(this,a,b)};
links.dnd=function(){function a(a,b){if(!i){i=b;var c=!0;if(i.dragStart){var d={};l={dataTransfer:{dragArea:i.element,dropArea:void 0,data:d,getData:function(a){return d[a]},setData:function(a,b){d[a]=b},clearData:function(a){delete d[a]}},clientX:a.clientX,clientY:a.clientY};c=i.dragStart(l)!==!1}if(c){c=void 0;k=document.createElement("div");k.style.position="absolute";typeof i.dragImage=="string"?(k.innerHTML=i.dragImage,n=-i.dragImageOffsetX||0,p=-i.dragImageOffsetY||0):i.dragImage?(k.appendChild(i.dragImage),
n=-i.dragImageOffsetX||0,p=-i.dragImageOffsetY||0):(c=i.element.cloneNode(!0),n=(a.clientX||0)-e(i.element),p=(a.clientY||0)-g(i.element),c.style.left="0px",c.style.top="0px",c.style.opacity="0.7",c.style.filter="alpha(opacity=70)",k.appendChild(c));document.body.appendChild(k);if(r==void 0)r=document.body.style.cursor;document.body.style.cursor="move"}else i=void 0}}function b(a,b){if(b&&b!="none"){if(!a||a.toLowerCase()=="all")return b;if(a.toLowerCase().indexOf(b.toLowerCase())!=-1)return b}}function c(a,
b,c,d){a.addEventListener?(d===void 0&&(d=!1),b==="mousewheel"&&navigator.userAgent.indexOf("Firefox")>=0&&(b="DOMMouseScroll"),a.addEventListener(b,c,d)):a.attachEvent("on"+b,c)}function d(a,b,c,d){a.removeEventListener?(d===void 0&&(d=!1),b==="mousewheel"&&navigator.userAgent.indexOf("Firefox")>=0&&(b="DOMMouseScroll"),a.removeEventListener(b,c,d)):a.detachEvent("on"+b,c)}function f(a){if(!a)a=window.event;a.preventDefault?a.preventDefault():a.returnValue=!1}function e(a){for(var b=0;a!=null;)b+=
a.offsetLeft,a=a.offsetParent;return b}function g(a){for(var b=0;a!=null;)b+=a.offsetTop,a=a.offsetParent;return b}var h=[],j=[],i=void 0,k=void 0,n=0,p=0,l={},q=void 0,o=void 0,r=void 0;return{makeDraggable:function(u,t){var v={element:u};t&&links.TreeGrid.extend(v,t);h.push(v);var w=function(h){h=h||window.event;if(h.which?h.which==1:h.button==1)q=function(c){i!=void 0||a(c,v);if(k){if(k)k.style.left=c.clientX-n+"px",k.style.top=c.clientY-p+"px";l.clientX=c.clientX;l.clientY=c.clientY;for(var d=
c.clientX-n,h=c.clientY-p,t=k.clientWidth||i.element.clientWidth,o=k.clientHeight||i.element.clientHeight,u=d+t/2,q=h+o/2,s=void 0,r=0;r<j.length;r++){var m=j[r],d=e(m.element),h=g(m.element),t=m.element.clientWidth,o=m.element.clientHeight;if(u>d&&u<d+t&&q>h&&q<h+o&&!s&&b(i.effectAllowed,m.dropEffect)){if(s=m,!m.mouseOver){if(m.dragEnter)l.dataTransfer.dropArea=m,l.dataTransfer.dropEffect=void 0,m.dragEnter(l);m.mouseOver=!0}}else if(m.mouseOver){if(m.dragLeave)l.dataTransfer.dropArea=m,l.dataTransfer.dropEffect=
void 0,m.dragLeave(l);m.mouseOver=!1}}s?(l.dataTransfer.dropArea=s.element,l.dataTransfer.dropEffect=b(i.effectAllowed,s.dropEffect),s.dragOver&&s.dragOver(l)):(l.dataTransfer.dropArea=void 0,l.dataTransfer.dropEffect=void 0);i.drag&&i.drag(l)}f(c)},c(document,"mousemove",q),o=function(a){if(i!=void 0){k&&k.parentNode&&k.parentNode.removeChild(k);k=void 0;document.body.style.cursor=r||"";for(var c=r=void 0,e=0;e<j.length;e++){var g=j[e];if(g.mouseOver)g.dragLeave&&g.dragLeave(l),g.mouseOver=!1,c||
(c=g)}c?(l.dataTransfer.dropArea=c.element,l.dataTransfer.dropEffect=b(i.effectAllowed,c.dropEffect),l.dataTransfer.dropEffect&&c.drop&&c.drop(l)):(l.dataTransfer.dropArea=void 0,l.dataTransfer.dropEffect=void 0);i.dragEnd&&i.dragEnd(l);i=void 0;l={}}q&&(d(document,"mousemove",q),q=void 0);o&&(d(document,"mouseup",o),o=void 0);f(a)},c(document,"mouseup",o),f(h)};c(u,"mousedown",w);v.mouseDown=w},makeDroppable:function(a,b){var c={element:a,mouseOver:!1};b&&links.TreeGrid.extend(c,b);if(!c.dropEffect)c.dropEffect=
"link";j.push(c)},removeDraggable:function(a){for(var b=0;b<h.length;){var c=h[b];c.element==a?(d(c.element,"mousedown",c.mouseDown),h.splice(b,1)):b++}},removeDroppable:function(a){for(var b=0;b<j.length;)j[b].element==a?j.splice(b,1):b++}}}();
links.events=links.events||{listeners:[],indexOf:function(a){for(var b=this.listeners,c=0,d=this.listeners.length;c<d;c++){var f=b[c];if(f&&f.object==a)return c}return-1},addListener:function(a,b,c){var d=this.listeners[this.indexOf(a)];d||(d={object:a,events:{}},this.listeners.push(d));a=d.events[b];a||(a=[],d.events[b]=a);a.indexOf(c)==-1&&a.push(c)},removeListener:function(a,b,c){var a=this.indexOf(a),d=this.listeners[a];if(d){var f=d.events[b];f&&(c=f.indexOf(c),c!=-1&&f.splice(c,1),f.length==
0&&delete d.events[b]);var b=0,d=d.events,e;for(e in d)d.hasOwnProperty(e)&&b++;b==0&&delete this.listeners[a]}},removeAllListeners:function(){this.listeners=[]},trigger:function(a,b,c){if(a=this.listeners[this.indexOf(a)])if(b=a.events[b])for(var a=0,d=b.length;a<d;a++)b[a](c)}};links.TreeGrid.addEventListener=function(a,b,c,d){a.addEventListener?(d===void 0&&(d=!1),b==="mousewheel"&&navigator.userAgent.indexOf("Firefox")>=0&&(b="DOMMouseScroll"),a.addEventListener(b,c,d)):a.attachEvent("on"+b,c)};
links.TreeGrid.removeEventListener=function(a,b,c,d){a.removeEventListener?(d===void 0&&(d=!1),b==="mousewheel"&&navigator.userAgent.indexOf("Firefox")>=0&&(b="DOMMouseScroll"),a.removeEventListener(b,c,d)):a.detachEvent("on"+b,c)};links.TreeGrid.getTarget=function(a){if(!a)a=window.event;var b;if(a.target)b=a.target;else if(a.srcElement)b=a.srcElement;if(b.nodeType!==void 0&&b.nodeType==3)b=b.parentNode;return b};
links.TreeGrid.getItemFromTarget=function(a){for(;a;){if(a.treeGridType=="item"&&a.item)return a.item;a=a.parentElement}};links.TreeGrid.stopPropagation=function(a){if(!a)a=window.event;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0};links.TreeGrid.preventDefault=function(a){if(!a)a=window.event;a.preventDefault?a.preventDefault():a.returnValue=!1};
